#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 20 17:24:08 2019

@author: Nigel
"""

# Cracking the Coding Interview Chapter 4

# Python Min Heap Implementation
import heapq

H = [21,1,45,78,3,5]
heapq.heapify(H)
print(H)